version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./Art:/usr/share/nginx/html/Art
    networks:
      - animation-network
networks:
  animation-network:
    driver: bridge
