name: Kickoff Post Merge Jobs

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  kickoff-post-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/post-merge.yml
