name: Kickoff Post Merge Jobs

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  kickoff-post-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call post merge jobs
        uses: ./.github/workflows/post-merge.yml
